### ISSUE TITLE
new class "small non coding RNA"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1043]
I started to tag some ncRNAs with 
/db_xref="SO:0002247" (small non-coding RNA)

Do we automatically recognise these in Chado, or does it need adding to a mini ontology

**Comment by kimrutherford** [comment]
> I started to tag some ncRNAs with
> /db_xref="SO:0002247" (small non-coding RNA)

That should probably be `/SO="SO:0002247"` to set the feature type in Chado.

> Do we automatically recognise these in Cahdo, or does it need adding to a mini ontology

We load this OBO file to get the SO terms:
https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/master/Ontology_Files/so-simple.obo

SO:0002247 is in there and in Chado.

**Comment by ValWood** [comment]
I fixed the ones I did so far:

chromosome1.contig:FT                   /SO="SO:0002247"
chromosome1.contig:FT                   /SO="SO:0002247"
chromosome1.contig:FT                   /SO="SO:0002247"
chromosome1.contig:FT                   /SO="SO:0002247"
chromosome2.contig:FT                   /SO="SO:0002247"
chromosome2.contig:FT                   /SO="SO:0002247"
chromosome2.contig:FT                   /SO="SO:0002247"
chromosome2.contig:FT                   /SO="SO:0002247"
chromosome2.contig:FT                   /SO="SO:0002247"
chromosome3.contig:FT                   /SO="SO:0002247"

**Comment by ValWood** [comment]
will check tomorrow...

**Comment by kimrutherford** [comment]
> will check tomorrow...

I checked and your features still have the type "ncRNA" in Chado after the later load.

I tracked down a bug in the loading code.  The /SO qualifiers were being ignored on gene features.  It was working for non-gene features like repeat_region, misc_feature and LTR which is probably why we hadn't noticed the problem before.

I've fixed the code and tested it on my desktop.  It should be OK in Chado and on the website on Friday morning.

**Comment by ValWood** [comment]
I see what you were saying now. The ones I annotated as sncRNA will still be ncRNA today. Got it!

**Comment by kimrutherford** [comment]
The sncRNA features are now loaded and queryable:
https://www.pombase.org/results/from/id/121545f2-db09-43e1-ae1f-898ca212fc35

**Comment by kimrutherford** [comment]
I think this can be closed now.  If you add any other RNA types, please let me know so I can add them to the configuration.
