### ISSUE TITLE
Don't load GO_REL into Chado

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1068]
Just making a ticket so I can move it out of my Inbox ;)

**Comment by kimrutherford** [comment]
I ran it last night and I'm looking at the results now.  So far the only problem I've found is:

```
log.2023-03-08-18-57-49.curation_tool_data:warning in 95ec493fb8fa90cf: can't find relation cvterm for: has_regulation_target in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
log.2023-03-08-18-57-49.curation_tool_data:warning in ebc037f099adf95b: can't find relation cvterm for: has_regulation_target in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
```

**Comment by ValWood** [comment]
I think these might be relations I wanted to fix anyway. I have an outstanding task to look at these but I have some confusion with the Canto prompts that I may need to ask you about. I am  on GO duty today and tomorrow so I may not get to it until next week.

**Comment by kimrutherford** [comment]
> I ran it last night and I'm looking at the results now. So far the only problem I've found is:

I didn't find any other problems.

I had forgotten but we already have a file of relations that aren't in gorel anymore:
`pombe-embl/mini-ontologies/gene_ex_extension_relations.obo`

If there are any relations from gorel that we need we can add them to that file.

**Comment by ValWood** [comment]
log.2023-03-08-18-57-49.curation_tool_data:warning in 95ec493fb8fa90cf: can't find relation cvterm for: has_regulation_target in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype

This one I can't see has_regulation_target anywhere in the session. I may have fixed this a couple of days ago?

log.2023-03-08-18-57-49.curation_tool_data:warning in ebc037f099adf95b: can't find relation cvterm for: has_regulation_target in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype

I definitely looked at this one a couple of days ago and I'm puzzled by it.
I'm using the relation in Canto:

<img width="345" alt="Screenshot 2023-03-10 at 14 08 07" src="https://user-images.githubusercontent.com/7359272/224337008-8fb1d178-40f9-4c4e-9cb5-ff3733d98539.png">

Which displays as has_regulation target.

but all of the others appear correctly as "activates trancription of". 

I'm not sure how the same term can end up with 2 differnet Curation and display options though?

**Comment by ValWood** [comment]
<img width="375" alt="Screenshot 2023-03-10 at 14 11 21" src="https://user-images.githubusercontent.com/7359272/224337704-4c8ca4ad-1d9d-40ab-9c24-0d05264d6e30.png">

**Comment by ValWood** [comment]
The problem above appears to be the same issue as
https://github.com/pombase/pombase-config/issues/91

**Comment by kimrutherford** [comment]
> This one I can't see has_regulation_target anywhere in the session. I may have fixed this a couple of days ago?

Yep, sorry.  I was using out of date Canto data on my desktop.  With an updated version there are 4 warnings about sessions that have `has_regulation_target`:

  - [4172bbc99aeb070b](https://curation.pombase.org/pombe/curs/4172bbc99aeb070b/ro)
  - [aeaa06c0eac76f9e](https://curation.pombase.org/pombe/curs/aeaa06c0eac76f9e/ro)
  - [84dc6f3caefc7153](https://curation.pombase.org/pombe/curs/84dc6f3caefc7153/ro)
  - [ebc037f099adf95b](https://curation.pombase.org/pombe/curs/ebc037f099adf95b/ro)

**Comment by kimrutherford** [comment]
> I'm not sure how the same term can end up with 2 differnet Curation and display options though?

I think we need to have call about this.  I'm quite confused.

**Comment by ValWood** [comment]
It's on my list. Me too!

**Comment by ValWood** [comment]
[4172bbc99aeb070b](https://curation.pombase.org/pombe/curs/4172bbc99aeb070b/ro)
fixed (I think)

[aeaa06c0eac76f9e](https://curation.pombase.org/pombe/curs/aeaa06c0eac76f9e/ro)
I deleted this, and re-added, but it still displays as has regulation target

[84dc6f3caefc7153](https://curation.pombase.org/pombe/curs/84dc6f3caefc7153/ro)
[ebc037f099adf95b](https://curation.pombase.org/pombe/curs/ebc037f099adf95b/ro)

**Comment by kimrutherford** [comment]
> just this one behaving oddly and I can't figure out why?

What's odd about it?

> fixed (I think)

What got fixed?

> I deleted this, and re-added, but it still displays as has regulation target

I still don't understand the problem.  Should we configure "has_regulation_target" to display as "activates transcription of" in the website?  Or is this a Canto display problem?

Is the annotation wrong or is the display wrong?:  https://curation.pombase.org/pombe/curs/ebc037f099adf95b/ro

**Comment by kimrutherford** [comment]
As discussed, I've changed the configuration so that all the `has_regulation_target()` relations are now`has_input()`.  I've only just pushed the change so it won't be visible until Sunday.

**Comment by ValWood** [comment]
I no longer see the rst2 has_input mug14, BUT that could be because the session was out of approval  when the update was done, not sure....

**Comment by kimrutherford** [comment]
> I no longer see the rst2 has_input mug14, BUT that could be because the session was out of approval when the update was done, not sure....

Which session was that?  I can check if there's a problem.

**Comment by ValWood** [comment]
PMID: 34086083
curs/ebc037f099adf95b/ro
the extension has gone...?

**Comment by kimrutherford** [comment]
> the extension has gone...?

Hi Val.  I checked the backups.  The extension was there until the 14th.  I can't tell from the backup why it's gone.

**Comment by ValWood** [comment]
I must have deleted it. I added it back...

**Comment by ValWood** [comment]
I think these are now all fixed.

**Comment by kimrutherford** [comment]
Thanks Val.  I'm planning to remove gorel.obo from the load on Saturday night and see how it goes.  If there are any problems I'll just leave the Friday night load in place on pombase.org and revert the changes.

**Comment by ValWood** [comment]
sounds good

**Comment by kimrutherford** [comment]
> Thanks Val. I'm planning to remove gorel.obo from the load on Saturday night and see how it goes.

The nightly load failed because the BioGRID server was unreachable.  BioGRID seems OK now so I'll check the load again on Monday morning.

**Comment by kimrutherford** [comment]
> I'll check the load again on Monday morning.

I've had a look at the logs and it all seems OK without GOREL.  There are no extra warnings about unknown relations as far as I can see.

So I've updated pombase.org with last night's load.

I was confused by these new warnings:
```
line 15624: can't load annotation, GO:0070084 not found in database
line 16860: can't load annotation, GO:0070084 not found in database
line 36221: can't load annotation, GO:0042779 not found in database
```
until I realised that those two terms had been made obsolete between Thursday night's load and Sunday night's load.  My main confusion was that Amigo and QuickGO don't show them as obsolete.

The other confusing thing is that the line numbers reported in the GOA GAF log file are nonsense.  I'll fix that: pombase/pombase-chado#1086

I was also alarmed to see the number of "Microscopy" annotations had gone way down (11864 to 626), until I notice that "microscopy evidence" annotations had gone way up.  I'll fix that too: pombase/pombase-chado#1085

**Comment by kimrutherford** [comment]
> I've had a look at the logs and it all seems OK without GOREL.

I've spotted three annotations that will need fixing, I think.  These annotations aren't in the logs. They loaded successfully without loading GO_REL because we copied some GO_REL relations into `pombe-embl/mini-ontologies/gene_ex_extension_relations.obo`.  The relations in that file are supposed to only be used for expression annotations.

So I've just gone through the relations in `gene_ex_extension_relations.obo` and checked that no relations from there are used in GO annotations.  I found three, all component annotations using `not_exists_during`:

| gene       | term_and_extension                              |
| ---------- | ----------------------------------------------- |
| SPBC582.03 | nucleus [not_exists_during] cytokinesis         |
| SPCC4B3.15 | nucleus [not_exists_during] mitotic interphase  |
| SPBC3H7.01 | plasma membrane [not_exists_during] sporulation |

**Comment by ValWood** [comment]
> My main confusion was that Amigo and QuickGO don't show them as obsolete.

Amigo only updates once a month. Quickgo more often, but there has been a problem with the GO snapshot for a while so a bunch of GO changes probably just came through

**Comment by ValWood** [comment]
fixed

**Comment by kimrutherford** [comment]
I forgot to make this change to the japonicus build.  A recent update to the GO OBO file caused the japonicus build to fail for the last few days.

After removing go_rel from the load it seems to work again.  There was an inconsistency between gorel and the GO OBO relations.
