### ISSUE TITLE
annotated gene changed in contig GO export

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#885]
Before:
<img width="999" alt="cdc7" src="https://user-images.githubusercontent.com/7359272/142723608-36d20c08-73a9-4cf1-9ba4-43d0c555f50c.png">

After
<img width="1139" alt="Screenshot 2021-11-20 at 10 50 51" src="https://user-images.githubusercontent.com/7359272/142723619-31a916c3-d121-4eb9-b5b8-1422ef3cf959.png">

I'm pretty sure I didn't change this, and I haven't really altered the  now GAF yet other than to delete a couple of rows.

in this annotation cdc7 phosphorylated cdc11
now its pld1 (which isn't a kinase).

**Comment by ValWood** [comment]
If you recreate the gaf, is it possible to save the changes that have been made since it was created?

**Comment by ValWood** [comment]
I see the probable cause, cdc7 has a synonym pld1.
Has anyone done any sort of global replace on the gaf files?

**Comment by kimrutherford** [comment]
Does that annotation come from Canto or the contig files?  If so I should be able to track down when it changed.

**Comment by ValWood** [comment]
It came from the contig files.I think the switch might have happened when the contig files were migrated to the GAF?

**Comment by kimrutherford** [comment]
> If you recreate the gaf, is it possible to save the changes that have been made since it was created?

That would be tricky.

I think I've fixed the issue.  It was picking up "pld1" from the synonym column in the legacy GAF file when it shouldn't have been.  It should have been using the systematic ID in column 2.  Sorry about that!

The GAF loader has lots of special cases to deal with the files from GOA.  For GOA we need to look in the synonym column for the pombe systematic ID.  When I changed the code to deal with transcript IDs I broke it the code.  It ended up looking in the synonym column first and used a gene name when it couldn't find a systematic ID there.

Hopefully it will be OK in the main site in the morning.

**Comment by kimrutherford** [comment]
> Hopefully it will be OK in the main site in the morning.

Fixed!  I think.

**Comment by ValWood** [comment]
note that in Canto  pld1 annotation still shows
curs/a2468b284d810cf8

**Comment by kimrutherford** [comment]
I hadn't update Canto.  Fixed now if you relaod.
